In [2]:
from __future__ import print_function
import torch
import numpy
from common import des
torch.__version__

'1.0.1'

In [28]:
def describe(x):
    print('x.type : {} '.format(x.type()))
    print('x.size : {}'.format(x.size()))
    print('x :\n{}\n'.format(x))

---

# 1 创建一个tensor

### 方法一：`torch.tensor`将列表转换为tensor

In [29]:
x = torch.tensor([[1,2,3],[4,5,6]])   #只能输入列表

describe(x)

x.type : torch.LongTensor 
x.size : torch.Size([2, 3])
x :
tensor([[1, 2, 3],
        [4, 5, 6]])



### 方法二：`torch.FloatTensor`,`torch.LongTensor`等指定形状创建tensor

In [31]:
x = torch.FloatTensor(3,3)
x1 = torch.Tensor(3,3)   #默认为FloatTensor，可通过更改pytorch设置改变其输出类型
y = torch.LongTensor(3,3)

describe(x)
describe(x1)
describe(y)

x.type : torch.FloatTensor 
x.size : torch.Size([3, 3])
x :
tensor([[ 0.0000e+00,  0.0000e+00, -8.0959e-13],
        [ 4.5909e-41,  2.8026e-45,  0.0000e+00],
        [        nan,         nan,  3.8519e-34]])

x.type : torch.FloatTensor 
x.size : torch.Size([3, 3])
x :
tensor([[ 0.0000e+00,  0.0000e+00, -8.0959e-13],
        [ 4.5909e-41,  2.8026e-45,  0.0000e+00],
        [        nan,         nan,  0.0000e+00]])

x.type : torch.LongTensor 
x.size : torch.Size([3, 3])
x :
tensor([[                0,                 0,                 0],
        [                0,                 0,              1160],
        [34058953218326528,                 0,                 0]])



### 方法三：`torch.rand()`生成元素在0，1之间的tensor

In [34]:
x = torch.rand(3, 3)

describe(x)

x.type : torch.FloatTensor 
x.size : torch.Size([3, 3])
x :
tensor([[0.1412, 0.3157, 0.4800],
        [0.7131, 0.1193, 0.6379],
        [0.9080, 0.4995, 0.5079]])



### 方法四：`torch.randn()`生成元素符合标准正态分布的tensor

In [42]:
# 构建 5x3 矩阵，只是分配了空间，未初始化
x = torch.randn(5, 5)

describe(x)

x[:,0:5:2]  #起始：终止+1：步长

x.type : torch.FloatTensor 
x.size : torch.Size([5, 5])
x :
tensor([[-1.0378, -1.6604,  1.5658,  0.1516, -1.3173],
        [-0.5129, -0.2630,  1.7001, -0.1972, -0.4703],
        [ 1.1221, -1.9905, -0.2341,  0.8430, -0.2531],
        [-0.9556,  0.9015,  0.4099, -0.7484,  0.9703],
        [-0.7072, -0.9884, -0.5526, -0.7766,  1.1795]])



tensor([[-1.0378,  1.5658, -1.3173],
        [-0.5129,  1.7001, -0.4703],
        [ 1.1221, -0.2341, -0.2531],
        [-0.9556,  0.4099,  0.9703],
        [-0.7072, -0.5526,  1.1795]])

### 方法五：`torch.zeros()`生成全0的tensor,`torch,ones`生成全1的tensor

In [44]:
x = torch.zeros(3,3)
x1 = torch.ones(3,3)
describe(x)
describe(x1)

x.type : torch.FloatTensor 
x.size : torch.Size([3, 3])
x :
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

x.type : torch.FloatTensor 
x.size : torch.Size([3, 3])
x :
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])



### 方法六：使用`torch.from_numpy()`将一个numpy数组转为tensor

In [49]:
import numpy as np

x = np.random.rand(3,3)

print(x)

[[0.57940803 0.00371448 0.14503214]
 [0.22031266 0.06345736 0.67914008]
 [0.91976657 0.7093897  0.21162536]]


In [50]:
x1 = torch.from_numpy(x)

describe(x1)

x.type : torch.DoubleTensor 
x.size : torch.Size([3, 3])
x :
tensor([[0.5794, 0.0037, 0.1450],
        [0.2203, 0.0635, 0.6791],
        [0.9198, 0.7094, 0.2116]], dtype=torch.float64)



---

# 2 tensor和numpy数组共享内存

In [54]:
x = np.random.randn(3,3)
x1 = torch.from_numpy(x)

x,x1

(array([[ 1.79764944,  0.17898194, -1.26026973],
        [ 0.86725058, -0.94388857,  0.50465909],
        [-1.86833115,  0.58828118,  0.21412948]]),
 tensor([[ 1.7976,  0.1790, -1.2603],
         [ 0.8673, -0.9439,  0.5047],
         [-1.8683,  0.5883,  0.2141]], dtype=torch.float64))

In [56]:
x1.add_(1)

x,x1  #数值同时变化

(array([[3.79764944, 2.17898194, 0.73973027],
        [2.86725058, 1.05611143, 2.50465909],
        [0.13166885, 2.58828118, 2.21412948]]),
 tensor([[3.7976, 2.1790, 0.7397],
         [2.8673, 1.0561, 2.5047],
         [0.1317, 2.5883, 2.2141]], dtype=torch.float64))

In [60]:
x = torch.randn(3,3)
x1=x.numpy()
x,x1

(tensor([[-1.4247, -1.5849,  1.3106],
         [ 0.3636, -0.3092, -1.3316],
         [ 0.1243,  1.6936, -0.3583]]),
 array([[-1.4246763 , -1.5848707 ,  1.3106009 ],
        [ 0.36355898, -0.3091837 , -1.3315983 ],
        [ 0.12427144,  1.6935744 , -0.3583063 ]], dtype=float32))

In [61]:
x.add_(1)

x,x1  #数值同时变化

(tensor([[-0.4247, -0.5849,  2.3106],
         [ 1.3636,  0.6908, -0.3316],
         [ 1.1243,  2.6936,  0.6417]]),
 array([[-0.4246763 , -0.5848707 ,  2.3106008 ],
        [ 1.363559  ,  0.6908163 , -0.33159828],
        [ 1.1242714 ,  2.6935744 ,  0.6416937 ]], dtype=float32))

---

# 3 区分torch.tensor(3)与torch.tensor([3])

tensor(3)是一个**0dim**的tensor,而torch.tensor([3])是一个**1dim**的tensor

In [69]:
x = torch.tensor(3)
x1 = torch.tensor([3])

x.size(),x1.size()

(torch.Size([]), torch.Size([1]))

---

# 4 tensor加法

### 方法1：直接x+y

In [70]:
x = torch.ones(3,3)
y = torch.ones(3,3)

In [72]:
add1 = x+y

add1

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

### 方法二：用`.add()`方法

In [74]:
add2 = torch.add(x,y)

add2

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

### 方法三：用`.add(x,y,out)`方法

In [81]:
add3 = x.clone().detach()   #定义add3，大小与x一样

add3

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [80]:
torch.add(x,y,out=add3)

add3

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

---

# 5 转为GPU的Tensor

In [83]:
x = torch.ones(3,3)

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

x = x.to(device)

describe(x)

x.type : torch.cuda.FloatTensor 
x.size : torch.Size([3, 3])
x :
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')



# 6 创建`reqires_grad=True`的tensor

In [87]:
x = torch.ones(2,3,requires_grad=True)

describe(x)

x.type : torch.FloatTensor 
x.size : torch.Size([2, 3])
x :
tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)



In [88]:
x = torch.FloatTensor(2,3,requires_grad=True)

TypeError: new() received an invalid combination of arguments - got (int, int, requires_grad=bool), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
 * (object data, torch.device device)


In [90]:
x = torch.FloatTensor(2,3)
x.requires_grad=True

describe(x)

x.type : torch.FloatTensor 
x.size : torch.Size([2, 3])
x :
tensor([[5.5181e+26, 4.5909e-41, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]], requires_grad=True)



# 7 求梯度`.backward()`与`.grad`

In [118]:
x = torch.ones(2,2,requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [119]:
y = x.sum()

y

tensor(4., grad_fn=<SumBackward0>)

In [120]:
y.backward()

In [121]:
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])
